### ISSUE TITLE
[FE] Prettier, Eslint 실행 문제 

### ISSUE THREAD

**Issue by iris-starry** [CODE-U-S/CodeUS#20]
### 🐞설명

1. .eslintrc.cjs, eslint.config.js ESLint 두 개의 파일이 있어서 충돌이 발생합니다. 
2. Prettier, Eslint 실행 명령어 정의가 안되어 있어요!

결론적으로 Prettier, ESLint 모두 재기능을 하지 않습니다.

### 📄 로그

```shell
표면적으로 드러나는 로그는 없음.
```

### 🌏 환경

Windows 11

**Comment by doyou0012** [comment]
#5 Prettier 및 ESLint 설정 이슈에 업데이트 했습니다!
